language: python
before_install:
  - sudo apt-get update -qq
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls
python:
  - "3.6"
  - "3.7"
script:
 - pycodestyle __init__.py
 - pytest --rootdir=test/unittests/ --cov unittests/
